# Site settings
title: Cooper Pellaton
email: c@cepp.ch
author: Cooper Pellaton
description: "Personal website and blog of Cooper Pellaton"
lang: en
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cepp.ch"
twitter:
    username: WBINVD
social:
    links:
        - https://github.com/cooperpellaton
        - https://www.linkedin.com/in/cooperpellaton/
        - https://bsky.app/profile/cooper.pellaton.is
mastodon: "https://hachyderm.io/@loop"
favicon: /assets/images/favicon.ico
permalink: pretty

# Build settings
markdown: kramdown
timezone: America/Los_Angeles

# Plugins
plugins:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag

# Exclude from processing
exclude:
    - Gemfile
    - Gemfile.lock
    - .jekyll-cache
    - gemfiles
    - .direnv
    - .envrc
    - flake.nix
    - flake.lock

# Front matter defaults
defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: "post"
          comments: false
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "default"
