# Site settings
title: Cooper Pellaton
email: c@cepp.ch
author: Cooper Pellaton
keywords: Cooper Pellaton, Cooper Eloy Pierre Pellaton, CEPP, CPellaton, Pellatonc, Pellatoner, WBINVD, c__p_r, engineer, Memora Health, Alibaba, Video++, VideoJJ, Cigna, China, Chinese, Switzerland, Swiss, French, English, Pellaton
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cepp.ch"
twitter:
  username: WBINVD
  card: summary
social:
  links:
    - https://github.com/cooperpellaton
mastodon: "https://hachyderm.io/@loop"
favicon: /assets/images/favicon.ico
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
