# Site settings
title: Cooper Pellaton
email: c@cepp.ch
description: > # this means to ignore newlines until "baseurl:"
  The personal musings of (the one and only) Cooper Pellaton.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cepp.ch"
twitter_username: WBINVD
github_username:  cooperpellaton
favicon: /assets/images/favicon.ico
theme-color: "#778899"
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
