# Site settings
title: Cooper Pellaton
email: c@cepp.ch
author: Cooper Pellaton
description: The personal musings of Cooper Pellaton.
keywords: Cooper Pellaton, Cooper Eloy Pierre Pellaton, CEPP, CPellaton, Pellatonc, Pellatoner, WBINVD, c__p_r, engineer, Memora Health, Alibaba, Video++, VideoJJ, Cigna, China, Chinese, Switzerland, Swiss, French, English, Pellaton
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cepp.ch"
twitter_username: WBINVD
github_username:  cooperpellaton
favicon: /assets/images/favicon.ico
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
